In [23]:
import h5py    
import numpy as np  
import os
import pandas as pd
import pickle as pkl
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold

In [4]:
label1=pd.read_csv('data/label1_test.csv')
label2=pd.read_csv('data/label2_test.csv')
label3=pd.read_csv('data/label3_test.csv')

In [7]:
kf = KFold(n_splits=5,shuffle=True)

In [8]:
for train_index, test_index in kf.split(label1):
    print(train_index,test_index)

[    0     1     2 ... 16173 16174 16175] [    9    10    21 ... 16152 16167 16172]
[    0     1     2 ... 16172 16174 16175] [    3     6    11 ... 16168 16169 16173]
[    0     1     3 ... 16172 16173 16175] [    2    20    23 ... 16165 16171 16174]
[    0     1     2 ... 16172 16173 16174] [    4    16    17 ... 16166 16170 16175]
[    2     3     4 ... 16173 16174 16175] [    0     1     5 ... 16150 16161 16163]


In [38]:
feature=pd.read_csv('data/bio_feature_test.csv')
clf = tree.DecisionTreeClassifier(max_depth=10)
clf.fit(feature.loc[train_index.tolist()], label1.loc[train_index.tolist()])
print(algo )
print(accuracy_score( label1.loc[train_index.tolist()], clf.predict(feature.loc[train_index.tolist()])))
print(accuracy_score( label1.loc[test_index.tolist()], clf.predict(feature.loc[test_index.tolist()])))

deep
0.9945908353295727
0.9752704791344667


In [39]:
feature=pd.read_csv('data/bio_feature_test.csv')
clf = tree.DecisionTreeClassifier(max_depth=10)
clf.fit(feature.loc[train_index.tolist()], label2.loc[train_index.tolist()])
print('ori')
print(accuracy_score( label2.loc[train_index.tolist()], clf.predict(feature.loc[train_index.tolist()])))
print(accuracy_score( label2.loc[test_index.tolist()], clf.predict(feature.loc[test_index.tolist()])))

ori
0.9332354532107257
0.8701700154559505


In [40]:
feature=pd.read_csv('data/bio_feature_test.csv')
clf = tree.DecisionTreeClassifier(max_depth=10)
clf.fit(feature.loc[train_index.tolist()], label3.loc[train_index.tolist()])
print('ori')
print(accuracy_score( label3.loc[train_index.tolist()], clf.predict(feature.loc[train_index.tolist()])))
print(accuracy_score( label3.loc[test_index.tolist()], clf.predict(feature.loc[test_index.tolist()])))

ori
0.8317749787497102
0.7338485316846987


In [34]:
algo_list=['CCA','metaCCA','KCCA','deep']

In [41]:
for algo in algo_list:
    feature=pd.read_csv('data/'+algo+'_fe.csv',index_col=[0])
    clf = tree.DecisionTreeClassifier(max_depth=10)
    clf.fit(feature.loc[train_index.tolist()], label1.loc[train_index.tolist()])
    print(algo )
    print(accuracy_score( label1.loc[train_index.tolist()], clf.predict(feature.loc[train_index.tolist()])))
    print(accuracy_score( label1.loc[test_index.tolist()], clf.predict(feature.loc[test_index.tolist()])))

CCA
0.9942044664245422
0.9706336939721792
metaCCA
0.9897225871261881
0.9666151468315302
KCCA
0.9998454524379878
0.9959814528593508
deep
0.9959817633876825
0.9799072642967542


In [42]:
for algo in algo_list:
    feature=pd.read_csv('data/'+algo+'_fe.csv',index_col=[0])
    clf = tree.DecisionTreeClassifier(max_depth=10)
    clf.fit(feature.loc[train_index.tolist()], label2.loc[train_index.tolist()])
    print(algo )
    print(accuracy_score( label2.loc[train_index.tolist()], clf.predict(feature.loc[train_index.tolist()])))
    print(accuracy_score( label2.loc[test_index.tolist()], clf.predict(feature.loc[test_index.tolist()])))

CCA
0.9019395719032532
0.8584234930448222
metaCCA
0.9089714859748087
0.852241112828439
KCCA
0.9299126806274631
0.9217928902627511
deep
0.9129124488061201
0.8754250386398763


In [43]:
for algo in algo_list:
    feature=pd.read_csv('data/'+algo+'_fe.csv',index_col=[0])
    clf = tree.DecisionTreeClassifier(max_depth=10)
    clf.fit(feature.loc[train_index.tolist()], label3.loc[train_index.tolist()])
    print(algo )
    print(accuracy_score( label3.loc[train_index.tolist()], clf.predict(feature.loc[train_index.tolist()])))
    print(accuracy_score( label3.loc[test_index.tolist()], clf.predict(feature.loc[test_index.tolist()])))

CCA
0.7973881462019936
0.7174652241112829
metaCCA
0.804265512711537
0.7137557959814529
KCCA
0.7994745382891585
0.7814528593508501
deep
0.7729696314040646
0.7227202472952087


In [53]:
for algo in algo_list:
    feature=pd.read_csv('data/'+algo+'_ta.csv',index_col=[0])
    clf = tree.DecisionTreeClassifier(max_depth=20)
    clf.fit(feature.loc[train_index.tolist()], label1.loc[train_index.tolist()])
    print(algo )
    print(accuracy_score( label1.loc[train_index.tolist()], clf.predict(feature.loc[train_index.tolist()])))
    print(accuracy_score( label1.loc[test_index.tolist()], clf.predict(feature.loc[test_index.tolist()])))

CCA
1.0
1.0
metaCCA
1.0
1.0
KCCA
1.0
1.0
deep
1.0
1.0


In [56]:
for algo in algo_list:
    feature=pd.read_csv('data/'+algo+'_ta.csv',index_col=[0])
    clf = tree.DecisionTreeClassifier(max_depth=25)
    clf.fit(feature.loc[train_index.tolist()], label2.loc[train_index.tolist()])
    print(algo )
    print(accuracy_score( label2.loc[train_index.tolist()], clf.predict(feature.loc[train_index.tolist()])))
    print(accuracy_score( label2.loc[test_index.tolist()], clf.predict(feature.loc[test_index.tolist()])))

CCA
1.0
1.0
metaCCA
1.0
1.0
KCCA
0.9988408932849084
0.9984544049459042
deep
0.997063596321768
0.9984544049459042


In [55]:
for algo in algo_list:
    feature=pd.read_csv('data/'+algo+'_ta.csv',index_col=[0])
    clf = tree.DecisionTreeClassifier(max_depth=25)
    clf.fit(feature.loc[train_index.tolist()], label3.loc[train_index.tolist()])
    print(algo )
    print(accuracy_score( label3.loc[train_index.tolist()], clf.predict(feature.loc[train_index.tolist()])))
    print(accuracy_score( label3.loc[test_index.tolist()], clf.predict(feature.loc[test_index.tolist()])))

CCA
0.9666950003863689
0.9690880989180835
metaCCA
0.9471447337918244
0.9437403400309119
KCCA
0.9444401514566108
0.9443585780525502
deep
0.9636040491461247
0.9675425038639877
