In [1]:
import torch
import pandas as pd
from linear_cca import linear_cca
from DeepCCAModels import DeepCCA
from main import Solver
import numpy as np
torch.set_default_tensor_type(torch.DoubleTensor)

In [2]:
def make_tensor(data_xy):
    data_x, data_y = data_xy
    data_x = torch.tensor(data_x)
    data_y = np.asarray(data_y, dtype='int32')
    return data_x, data_y

In [3]:
data1=pd.read_csv('bio_feature_toy.csv')
data2=pd.read_csv('label_one_hot_toy.csv')

In [4]:
data1.shape

(10000, 224)

In [5]:
data2.shape

(10000, 97)

In [6]:
model = DeepCCA([256, 256, 256, 10], [256, 256, 256, 10], 224,97, 10, False).double()

solver = Solver(model, linear_cca(), 10, 10, 800,1e-3, 1e-5)

[ INFO : 2021-09-29 20:06:13,834 ] - DataParallel(
  (module): DeepCCA(
    (model1): MlpNet(
      (layers): ModuleList(
        (0): Sequential(
          (0): Linear(in_features=224, out_features=256, bias=True)
          (1): Sigmoid()
          (2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=False, track_running_stats=True)
        )
        (1): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Sigmoid()
          (2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=False, track_running_stats=True)
        )
        (2): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): Sigmoid()
          (2): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=False, track_running_stats=True)
        )
        (3): Sequential(
          (0): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=False, track_running_stats=True)
          (1): Linear(in_features=256, out_features=10, bias=True)
        )
    

In [9]:
solver.fit(torch.tensor(data1.values), torch.tensor(data2.values))
# TODO: Save linear_cca model if needed

D:\project\CCA\CCA\code\DeepCCA-master\objectives.py:54: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  ..\torch\csrc\utils\python_arg_parser.cpp:766.)
  posInd1 = torch.gt(D1, eps).nonzero()[:, 0]
[ INFO : 2021-09-29 20:07:33,673 ] - Epoch 1/10 - time: 1.03 - training_loss: -7.8340
[ INFO : 2021-09-29 20:07:34,714 ] - Epoch 2/10 - time: 1.04 - training_loss: -8.4908
[ INFO : 2021-09-29 20:07:35,757 ] - Epoch 3/10 - time: 1.04 - training_loss: -8.7798
[ INFO : 2021-09-29 20:07:36,709 ] - Epoch 4/10 - time: 0.95 - training_loss: -8.9497
[ INFO : 2021-09-29 20:07:37,729 ] - Epoch 5/10 - time: 1.02 - training_loss: -9.0643
[ INFO : 2021-09-29 20:07:38,750 ] - Epoch 6/10 - time: 1.02 - training_loss: -9.1492
[ INFO : 2021-09-29 20:07:39,739 ] - Epoch 7/10 - time: 0.99 - training_loss: -9.2142
[ INFO : 2021-09-29 20:07:40,881 ] - Epoch 8/10 - time: 1.14 - training_lo

U.size() torch.Size([10])
V.size() torch.Size([10, 10])
torch.Size([10])
tensor([-0.9962, -0.9941, -0.9918, -0.9878, -0.9815, -0.9680, -0.9589, -0.9461,
        -0.9411, -0.9100])
U.size() torch.Size([10])
V.size() torch.Size([10, 10])
torch.Size([10])
tensor([-0.9951, -0.9943, -0.9918, -0.9844, -0.9784, -0.9744, -0.9706, -0.9535,
        -0.9345, -0.9100])
U.size() torch.Size([10])
V.size() torch.Size([10, 10])
torch.Size([10])
tensor([-0.9956, -0.9934, -0.9873, -0.9863, -0.9840, -0.9758, -0.9618, -0.9543,
        -0.9374, -0.9286])
U.size() torch.Size([10])
V.size() torch.Size([10, 10])
torch.Size([10])
tensor([-0.9956, -0.9924, -0.9903, -0.9879, -0.9856, -0.9812, -0.9718, -0.9451,
        -0.9416, -0.9141])
U.size() torch.Size([10])
V.size() torch.Size([10, 10])
torch.Size([10])
tensor([-0.9950, -0.9928, -0.9906, -0.9871, -0.9808, -0.9730, -0.9496, -0.9411,
        -0.9259, -0.9045])
U.size() torch.Size([10])
V.size() torch.Size([10, 10])
torch.Size([10])
tensor([-0.9950, -0.9944, -

In [12]:
loss_mean, losses,outputs = solver.test(torch.tensor(data1.values), torch.tensor(data2.values), True)

U.size() torch.Size([10])
V.size() torch.Size([10, 10])
torch.Size([10])
tensor([-0.9962, -0.9941, -0.9918, -0.9878, -0.9815, -0.9680, -0.9589, -0.9461,
        -0.9411, -0.9100])
U.size() torch.Size([10])
V.size() torch.Size([10, 10])
torch.Size([10])
tensor([-0.9951, -0.9943, -0.9918, -0.9844, -0.9784, -0.9744, -0.9706, -0.9535,
        -0.9345, -0.9100])
U.size() torch.Size([10])
V.size() torch.Size([10, 10])
torch.Size([10])
tensor([-0.9956, -0.9934, -0.9873, -0.9863, -0.9840, -0.9758, -0.9618, -0.9543,
        -0.9374, -0.9286])
U.size() torch.Size([10])
V.size() torch.Size([10, 10])
torch.Size([10])
tensor([-0.9956, -0.9924, -0.9903, -0.9879, -0.9856, -0.9812, -0.9718, -0.9451,
        -0.9416, -0.9141])
U.size() torch.Size([10])
V.size() torch.Size([10, 10])
torch.Size([10])
tensor([-0.9950, -0.9928, -0.9906, -0.9871, -0.9808, -0.9730, -0.9496, -0.9411,
        -0.9259, -0.9045])
U.size() torch.Size([10])
V.size() torch.Size([10, 10])
torch.Size([10])
tensor([-0.9950, -0.9944, -

In [13]:
for i in range(10):
    print (np.corrcoef(outputs[0][:,i], outputs[1][:, i])[0,1])

0.9941658463036706
0.9930897624058157
0.9894035084200657
0.9859055411033956
0.9850351279221474
0.969776985948029
0.96166605367725
0.9565543832116701
0.935620750456905
0.9316055471701336


In [14]:
loss_mean

-0.9691300009474669

In [15]:
np.array(losses).reshape(-1).shape

(130,)

In [16]:
np.min(np.array(losses))

-0.9966211369332887

In [17]:
outputs[0].shape

(10000, 10)

In [18]:
pd.DataFrame(outputs[0]).to_csv('deep_10_fe.csv')

In [19]:
pd.DataFrame(outputs[1]).to_csv('deep_10_ta.csv')