In [1]:
import h5py    
import numpy as np    
import scanpy as sc
import os
import pandas as pd
import pickle as pkl
import matplotlib as mpl
import matplotlib.pyplot as plt
import scipy.stats

sc.settings.verbosity = 3

In [2]:
f1 = h5py.File('../data/pbmc_multimodal.h5','r+') 

In [3]:
print("Keys: %s" % f1.keys())

Keys: <KeysViewHDF5 ['active.ident', 'assays', 'cell.names', 'commands', 'graphs', 'images', 'meta.data', 'misc', 'neighbors', 'reductions', 'tools']>


In [4]:
for key in f1.keys():
    print(f1[key])

<HDF5 group "/active.ident" (2 members)>
<HDF5 group "/assays" (2 members)>
<HDF5 dataset "cell.names": shape (161764,), type "|O">
<HDF5 group "/commands" (1 members)>
<HDF5 group "/graphs" (2 members)>
<HDF5 group "/images" (0 members)>
<HDF5 group "/meta.data" (15 members)>
<HDF5 group "/misc" (0 members)>
<HDF5 group "/neighbors" (0 members)>
<HDF5 group "/reductions" (6 members)>
<HDF5 group "/tools" (0 members)>


## active.ident

In [5]:
f1['active.ident'].keys()

<KeysViewHDF5 ['levels', 'values']>

In [6]:
f1['active.ident']['levels'][:]

array(['CD14 Mono', 'CD4 TCM_1', 'CD8 Naive', 'NK_2', 'CD8 TEM_1',
       'CD16 Mono', 'B intermediate lambda', 'CD4 Naive', 'CD4 CTL',
       'B naive kappa', 'CD4 TCM_3', 'MAIT', 'CD4 TCM_2', 'CD8 TEM_2',
       'gdT_3', 'NK_1', 'CD8 TCM_1', 'dnT_2', 'B intermediate kappa',
       'B memory kappa', 'Doublet', 'pDC', 'CD8 TEM_5', 'gdT_1',
       'B naive lambda', 'NK_4', 'CD8 Proliferating', 'CD8 TCM_2',
       'Treg Naive', 'Plasma', 'CD4 TEM_1', 'Treg Memory', 'CD4 TEM_3',
       'CD8 TCM_3', 'cDC2_1', 'NK Proliferating', 'CD8 TEM_4', 'ASDC_pDC',
       'CD4 TEM_2', 'B memory lambda', 'dnT_1', 'HSPC', 'cDC2_2',
       'Platelet', 'NK_CD56bright', 'CD4 TEM_4', 'CD8 TEM_6',
       'CD8 Naive_2', 'gdT_2', 'NK_3', 'CD8 TEM_3', 'CD4 Proliferating',
       'Eryth', 'gdT_4', 'Plasmablast', 'cDC1', 'ASDC_mDC', 'ILC'],
      dtype=object)

In [7]:
f1['active.ident']['values'][:]

array([ 1,  2,  3, ..., 19,  6,  1])

# assays 
## include feature

In [8]:
f1['assays'].keys()

<KeysViewHDF5 ['ADT', 'SCT']>

In [9]:
f1['assays']['ADT'].keys()

<KeysViewHDF5 ['counts', 'data', 'features', 'misc', 'variable.features']>

In [10]:
for key in f1['assays']['ADT'].keys():
    try:
        print('*'*20)
        print(key)
        print(f1['assays']['ADT'][key])
        print(f1['assays']['ADT'][key][:])
        
    except:
        pass

********************
counts
<HDF5 group "/assays/ADT/counts" (3 members)>
********************
data
<HDF5 dataset "data": shape (161764, 228), type "<f8">
[[1.95916424 0.86914159 1.48523314 ... 0.55307644 1.04608444 1.72565693]
 [0.4322284  1.01422751 0.79594998 ... 0.66587988 0.85514588 1.37971736]
 [0.61381759 1.30390619 0.75610373 ... 0.6874892  0.75610373 1.04246048]
 ...
 [1.50685426 0.54914608 1.0656108  ... 0.25674036 0.25674036 1.16168749]
 [1.63537843 0.32520632 1.19570797 ... 0.45519093 0.51435145 2.10485699]
 [1.58503    0.64458811 1.61118685 ... 0.416905   0.23002318 2.07731277]]
********************
features
<HDF5 dataset "features": shape (228,), type "|O">
['CD39' 'Rat-IgG1-1' 'CD107a' 'CD62P' 'TCR-2' 'CD30' 'CD31' 'CD34' 'CD35'
 'CD36' 'CD223' 'TIGIT' 'TCR-V-9' 'CD226' 'CD178' 'CD319' 'CD171'
 'Siglec-8' 'CD340' 'Rat-IgG2b' 'VEGFR-3' 'CD29' 'CD62E' 'CD4-2' 'CD4-1'
 'CD22' 'CD3-1' 'CD20' 'CD27' 'CD45RB' 'CD25' 'CD24' 'CD146' 'Galectin-9'
 'CD142' 'CD141' 'CD294' 'Rat-IgG

In [11]:
f1['assays']['SCT'].keys()

<KeysViewHDF5 ['SCTModel.list', 'counts', 'data', 'features', 'misc', 'variable.features']>

In [19]:
for key in f1['assays']['SCT'].keys():
    try:
        print('*'*20)
        print(key)
        print(f1['assays']['SCT'][key])
        print(f1['assays']['SCT'][key][:])
        
    except:
        pass

********************
SCTModel.list
<HDF5 group "/assays/SCT/SCTModel.list" (1 members)>
********************
counts
<HDF5 group "/assays/SCT/counts" (3 members)>
********************
data
<HDF5 group "/assays/SCT/data" (3 members)>
********************
features
<HDF5 dataset "features": shape (20729,), type "|O">
['AL627309.1' 'AL669831.5' 'LINC00115' ... 'Z82244.2' 'AP001468.1'
 'AP001469.2']
********************
misc
<HDF5 group "/assays/SCT/misc" (0 members)>
********************
variable.features
<HDF5 dataset "variable.features": shape (5000,), type "|O">
['S100A9' 'GNLY' 'S100A8' ... 'ZNF546' 'AMT' 'ATG9A']


In [15]:
336935477/20729

16254.304452699118

In [14]:
for key in f1['assays']['SCT']['features'].keys():
    try:
        print('*'*20)
        print(key)
        print(f1['assays']['SCT']['features'][key])
        print(f1['assays']['SCT']['features'][key][:])
        
    except:
        pass

AttributeError: 'Dataset' object has no attribute 'keys'

In [12]:
for key in f1['assays']['SCT']['data'].keys():
    try:
        print('*'*20)
        print(key)
        print(f1['assays']['SCT']['data'][key])
        print(f1['assays']['SCT']['data'][key][:])
        
    except:
        pass

********************
data
<HDF5 dataset "data": shape (336935477,), type "<f8">
[0.69314718 0.69314718 0.69314718 ... 1.38629436 0.69314718 0.69314718]
********************
indices
<HDF5 dataset "indices": shape (336935477,), type "<i4">
[    1    19    23 ... 17866 18249 18702]
********************
indptr
<HDF5 dataset "indptr": shape (161765,), type "<i4">
[        0      2548      4163 ... 336928657 336932190 336935477]


In [24]:
for key in f1['assays']['SCT']['SCTModel.list']['refmodel']['feature.attributes'].keys():
    try:
        print('*'*20)
        print(key)
        print(f1['assays']['SCT']['SCTModel.list']['refmodel']['feature.attributes'][key])
        print(f1['assays']['SCT']['SCTModel.list']['refmodel']['feature.attributes'][key][:])
        
    except:
        pass

********************
(Intercept)
<HDF5 dataset "(Intercept)": shape (16378,), type "<f8">
[-14.01255302 -11.61790352 -12.25439758 ... -13.15957195 -12.59157931
 -12.26890393]
********************
_index
<HDF5 dataset "_index": shape (16378,), type "|O">
['AL627309.1' 'AL669831.5' 'LINC00115' ... 'AC007325.4' 'AL354822.1'
 'AC240274.1']
********************
detection_rate
<HDF5 dataset "detection_rate": shape (16378,), type "<f8">
[0.00234192 0.03178321 0.01739712 ... 0.01137504 0.0142188  0.01689528]
********************
genes_log_gmean_step1
<HDF5 dataset "genes_log_gmean_step1": shape (16378,), type "<i4">
[0 1 1 ... 0 0 1]
********************
gmean
<HDF5 dataset "gmean": shape (16378,), type "<f8">
[0.00162461 0.0231856  0.01226907 ... 0.00798411 0.01031552 0.01217165]
********************
log_umi
<HDF5 dataset "log_umi": shape (16378,), type "<f8">
[2.07188248 2.14451326 2.13796504 ... 2.25246817 2.17774459 2.13956335]
********************
residual_mean
<HDF5 dataset "residual_mea

## cell.names

In [11]:
f1['cell.names']

<HDF5 dataset "cell.names": shape (161764,), type "|O">

In [12]:
f1['cell.names'][:]

array(['L1_AAACCCAAGAAACTCA', 'L1_AAACCCAAGACATACA',
       'L1_AAACCCACAACTGGTT', ..., 'E2L8_TTTGTTGGTTAGTTCG',
       'E2L8_TTTGTTGGTTGGCTAT', 'E2L8_TTTGTTGTCTCATGGA'], dtype=object)

## commands

In [13]:
f1['commands'].keys()

<KeysViewHDF5 ['NormalizeData.ADT']>

In [14]:
f1['commands']['NormalizeData.ADT'].keys()

<KeysViewHDF5 ['assay', 'margin', 'normalization.method', 'scale.factor', 'verbose']>

In [15]:
for key in f1['commands']['NormalizeData.ADT'].keys():
    try:
        print('*'*20)
        print(key)
        print(f1['commands']['NormalizeData.ADT'][key])
        print(f1['commands']['NormalizeData.ADT'][key][:])
        
    except:
        pass

********************
assay
<HDF5 dataset "assay": shape (1,), type "|O">
['ADT']
********************
margin
<HDF5 dataset "margin": shape (1,), type "<f8">
[2.]
********************
normalization.method
<HDF5 dataset "normalization.method": shape (1,), type "|O">
['CLR']
********************
scale.factor
<HDF5 dataset "scale.factor": shape (1,), type "<f8">
[10000.]
********************
verbose
<HDF5 dataset "verbose": shape (1,), type "<i4">
[1]


## graphs

In [16]:
f1['graphs'].keys()

<KeysViewHDF5 ['wknn', 'wsnn']>

In [17]:
for key in f1['graphs']['wknn'].keys():
    try:
        print('*'*20)
        print(key)
        print( f1['graphs']['wknn'][key])
        print( f1['graphs']['wknn'][key][:])
        
    except:
        pass

********************
data
<HDF5 dataset "data": shape (8218424,), type "<f8">
[1. 1. 1. ... 1. 1. 1.]
********************
indices
<HDF5 dataset "indices": shape (8218424,), type "<i4">
[     0   1799   2016 ... 160573 161105 161763]
********************
indptr
<HDF5 dataset "indptr": shape (161765,), type "<i4">
[      0      41      74 ... 8218352 8218389 8218424]


In [18]:
for key in f1['graphs']['wsnn'].keys():
    try:
        print('*'*20)
        print(key)
        print( f1['graphs']['wsnn'][key])
        print( f1['graphs']['wsnn'][key][:])
        
    except:
        pass

********************
data
<HDF5 dataset "data": shape (19487586,), type "<f8">
[1.         0.07142857 0.07142857 ... 0.09090909 0.27659574 1.        ]
********************
indices
<HDF5 dataset "indices": shape (19487586,), type "<i4">
[     0    937   1505 ... 160270 161105 161763]
********************
indptr
<HDF5 dataset "indptr": shape (161765,), type "<i4">
[       0       86      155 ... 19487427 19487473 19487586]


In [19]:
'', '', ''

('', '', '')

## images

In [20]:
f1['images'].keys()

<KeysViewHDF5 []>

## meta.data

In [21]:
f1['meta.data'].keys()

<KeysViewHDF5 ['Phase', '_index', 'celltype.l1', 'celltype.l2', 'celltype.l3', 'donor', 'lane', 'nCount_ADT', 'nCount_RNA', 'nCount_SCT', 'nFeature_ADT', 'nFeature_RNA', 'nFeature_SCT', 'orig.ident', 'time']>

In [22]:
for key in f1['meta.data'].keys():
    try:
        print('*'*20)
        print(key)
        print( f1['meta.data'][key])
        print( f1['meta.data'][key][:])
        
    except:
        pass

********************
Phase
<HDF5 dataset "Phase": shape (161764,), type "|O">
['G1' 'G1' 'S' ... 'S' 'G1' 'G1']
********************
_index
<HDF5 dataset "_index": shape (161764,), type "|O">
['L1_AAACCCAAGAAACTCA' 'L1_AAACCCAAGACATACA' 'L1_AAACCCACAACTGGTT' ...
 'E2L8_TTTGTTGGTTAGTTCG' 'E2L8_TTTGTTGGTTGGCTAT' 'E2L8_TTTGTTGTCTCATGGA']
********************
celltype.l1
<HDF5 dataset "celltype.l1": shape (161764,), type "|O">
['Mono' 'CD4 T' 'CD8 T' ... 'B' 'Mono' 'Mono']
********************
celltype.l2
<HDF5 dataset "celltype.l2": shape (161764,), type "|O">
['CD14 Mono' 'CD4 TCM' 'CD8 Naive' ... 'B intermediate' 'CD16 Mono'
 'CD14 Mono']
********************
celltype.l3
<HDF5 dataset "celltype.l3": shape (161764,), type "|O">
['CD14 Mono' 'CD4 TCM_1' 'CD8 Naive' ... 'B intermediate kappa'
 'CD16 Mono' 'CD14 Mono']
********************
donor
<HDF5 dataset "donor": shape (161764,), type "|O">
['P2' 'P1' 'P4' ... 'P8' 'P5' 'P5']
********************
lane
<HDF5 dataset "lane": shape (16176

## misc

In [23]:
f1['misc'].keys()

<KeysViewHDF5 []>

## neighbors

In [24]:
f1['neighbors'].keys()

<KeysViewHDF5 []>

## reductions

In [25]:
f1['reductions'].keys()

<KeysViewHDF5 ['apca', 'aumap', 'pca', 'spca', 'umap', 'wnn.umap']>

## tools

In [26]:
f1['tools'].keys()

<KeysViewHDF5 []>